services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wp-volume:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/wordpress
    networks:
      - inception
    depends_on: 
      - wordpress
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kjolly/data/mariadb

  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kjolly/data/wordpress
